### ISSUE TITLE
mysql_connection_count no data

### ISSUE THREAD

**Issue by molixiaoge** [SigNoz/dashboards#89]
After adding MySQL collection configuration in Signoz, you can see other collected data, but there is no data for mysql_connection_count.

```
VersionInfo
 Signoz v0.55.0
 mysql 5.7.28
```
 

![图片](https://github.com/user-attachments/assets/6dc95e5e-fc41-4ea6-b901-7e553e72ad89)

![图片](https://github.com/user-attachments/assets/e82e83c4-1d3d-488c-8690-8b44203df3c7)

**Comment by molixiaoge** [comment]
ok

**Comment by thatsk** [comment]
@molixiaoge whats fix for this then ?

**Comment by molixiaoge** [comment]
Do not use the values of these fields
